spring:
  application.name: mcode-java
  datasource:
    url: jdbc:postgresql://localhost:5432/db_sales?currentSchema=school
    username: postgres
    password: prueba
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false # Helps to remove error org.hibernate.resource.transaction.backend.jdbc.internal.JdbcIsolationDelegate.sqlExceptionHelper()

server:
  port: 9090
  servlet:
    context-path: /mc

